# Configuration file for estatbib2json action
# This will launch (see Dockerfile) a pre-built Docker image from the pandoc container repository
# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#      https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

# credits: grazzja (Eurostat, Unit B1)
# since: 09/20

name: 'BibTeX to BibJSON'
inputs:
  bibtex-basename:
    description: "Basename of Eurostat bibliography source file"
    required: true
#    default: "eurostatref"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bibtex-basename }} 
