# action.yml
# See https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

name: 'BibTeX to BibJSON'
inputs:
  bibtex-basename:
    description: "Basename of Eurostat bibliography source file"
    required: true
#    default: "eurostatref"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bibtex-basename }} 
