name: Automated JSON bibliography creation from BibTeX file

on:
  push:
    branches:
      - master

jobs:
  estatbib2json:
    runs-on: ubuntu-latest
    name: Running estatbib2json action
    steps:
    - name: Checking out
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Convert BibTeX to BibJSON
      uses: ./.github/actions/estatbib2json
    - name: Commit BibJSON file 
      uses: EndBug/add-and-commit@v4
      with:
        message: "updating bibjson"
        add: "eurostatref.json"
        force: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
