name: Automated JSON bibliography creation from BibTeX file

on:
  push:
    branches:
      - master

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Run pandoc-citeproc on eurostatref.bib
        uses: docker://pandoc/core:2.9
      - run: echo '::set-env name=LANG::en_US.UTF-8'
      - run: echo '::set-env name=ESTAT_SOURCE_BIB::eurostatref.bib'
      - run: echo '::set-env name=ESTAT_TARGET_JSON::eurostatref.json'
      - run: pandoc-citeproc --bib2json ${{ ESTAT_SOURCE_BIB }} >  ${{ ESTAT_TARGET_JSON }}
